# Generated by Django 3.1.2 on 2020-10-09 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20201008_0617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'The Question', 'verbose_name_plural': "People's Questions"},
        ),
    ]
