# Generated by Django 3.1.2 on 2020-10-10 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20201009_1539'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
